---

- name: This is a simple Playbook.
  hosts: ubuntu_vm
  become: yes
  gather_facts: yes

  tasks:
    - name: 1. Ping the remote server
      ping:
    - name: 2. Create index file 
      file:
        path: /home/ubuntu/index.html
        state: touch

    - name: 3. Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes  # Ensures the package list is updated

    - name: 4. Restart Nginx Service
      service:
        name: nginx
        state: restarted  

    # # - name: 2. Un-Install git 
    # #   apt:
    # #     name: git
    # #     state: present   


    
